
{
    "success": true,
    "startDate": "2024-12-01",
    "endDate": "2024-12-31",
    "columns": [
        "Campaign",
        "Calls",
        "Orders",
        "Verified",
        "Verified Amount",
        "Verified Ticket Size",
        "Order Conversion",
        "Verified Conversion",
        "Verification %",
        "RPC (Revenue per Call)"
    ],
    "campaignReport": [
        {
            "Campaign": "Digital inbound",
            "Calls": 158079,
            "Orders": 22264,
            "Verified": 18833,
            "Verified Amount": 51271007,
            "Verified Ticket Size": 2722,
            "Order Conversion": "14%",
            "Verified Conversion": "12%",
            "Verification %": "85%",
            "RPC (Revenue per Call)": 324
        },
        {
            "Campaign": "Inbound_2",
            "Calls": 257798,
            "Orders": 44287,
            "Verified": 38526,
            "Verified Amount": 108503735,
            "Verified Ticket Size": 2816,
            "Order Conversion": "17%",
            "Verified Conversion": "15%",
            "Verification %": "87%",
            "RPC (Revenue per Call)": 421
        }
    ],
    "agentReport": [
        {
            "Campaign": "Aamir2553",
            "Calls": 2389,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "AarifaBT29",
            "Calls": 213,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "AartiBT10",
            "Calls": 2348,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "AbdulBT5",
            "Calls": 1560,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "Absar2653",
            "Calls": 2083,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "AdeebBT20",
            "Calls": 2568,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "AdityaBT21",
            "Calls": 1776,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "Adnan2996",
            "Calls": 2189,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "AdnanBT15",
            "Calls": 1411,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "AffanBT23",
            "Calls": 2547,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "AfreenBT26",
            "Calls": 2109,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "AfreenBT31",
            "Calls": 2679,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "AliBT16HYD",
            "Calls": 1764,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "Altaab2682",
            "Calls": 1935,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "AltafBT32",
            "Calls": 2594,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "AmaanBT19",
            "Calls": 2574,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "AmaanBT28",
            "Calls": 773,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "AmritBT1",
            "Calls": 2919,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "Anas_TL",
            "Calls": 663,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "Anas2110",
            "Calls": 2129,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "Anas3217",
            "Calls": 2163,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "AnasBT2",
            "Calls": 2205,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "AnishBT28",
            "Calls": 1903,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "AnnieBT28",
            "Calls": 2159,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "AnwarBT26",
            "Calls": 2401,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "AqdasBT19",
            "Calls": 2035,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "AqibBT18",
            "Calls": 2319,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "ArbazBT10",
            "Calls": 2011,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "ArbazBT7",
            "Calls": 2261,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "Arham2975",
            "Calls": 1930,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "ArwajBT27",
            "Calls": 2042,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "AsfanBT23",
            "Calls": 2310,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "AshikBT29",
            "Calls": 2240,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "AshokBT2",
            "Calls": 1978,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "AshrafBT27",
            "Calls": 1900,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "Asim2957",
            "Calls": 2607,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "Bilal2210A",
            "Calls": 2436,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "BilalBT26",
            "Calls": 1954,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "BulbulBT10",
            "Calls": 163,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "Chanchal434",
            "Calls": 3123,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "ChandniBT25",
            "Calls": 2161,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "DharmenderBT14",
            "Calls": 1910,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "DibyanshuBT23",
            "Calls": 2290,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "DikshaBT25",
            "Calls": 2342,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "DivyaBT13",
            "Calls": 3056,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "Dolly953",
            "Calls": 1519,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "DollyBT25",
            "Calls": 2327,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "DrAkhatarHYD",
            "Calls": 259,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "DrAli",
            "Calls": 1182,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "DrAnas1329",
            "Calls": 2161,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "DrAyush",
            "Calls": 1277,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "DrDawood",
            "Calls": 1098,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "DrMadhuri",
            "Calls": 312,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "DrMalikHYD",
            "Calls": 284,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "DrMerajHYD",
            "Calls": 1435,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "FaiyazBT3",
            "Calls": 2416,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "FaizaHYD09",
            "Calls": 334,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "Faizan1815",
            "Calls": 2459,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "FaizanBT1",
            "Calls": 2528,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "FaizanBT7",
            "Calls": 2794,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "FaizBT22",
            "Calls": 1443,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "Farhan1843",
            "Calls": 1944,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "Farman1319",
            "Calls": 1676,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "FarzanaBT26",
            "Calls": 1873,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "Feeroz3418",
            "Calls": 1711,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "FirdosBT16HYD",
            "Calls": 352,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "Firoz2884",
            "Calls": 1891,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "FurqanBT15",
            "Calls": 3014,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "Gaurav477",
            "Calls": 665,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "GauravBT20",
            "Calls": 2401,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "GauravYadav2027",
            "Calls": 2583,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "Haider462",
            "Calls": 22,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "HakeemTasabbur19_Hifzan_e_sehat_HOD",
            "Calls": 2855,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "HammadBT1",
            "Calls": 2550,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "HamzaBT2",
            "Calls": 2028,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "HasibBT28",
            "Calls": 1486,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "HimanshiBT7",
            "Calls": 2267,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "HimanshuBT21",
            "Calls": 892,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "HimanshuBT25",
            "Calls": 2072,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "HusainBT22",
            "Calls": 2384,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "IfrozBT14HYD",
            "Calls": 1632,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "ImranBT18",
            "Calls": 81,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "Imrankhan959",
            "Calls": 2016,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "InderjeetBT12",
            "Calls": 2357,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "IstyakBT14HYD",
            "Calls": 1773,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "Jahid_TL",
            "Calls": 617,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "JawwadBT17",
            "Calls": 2333,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "Junaid_TL",
            "Calls": 18,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "JyotiBT23",
            "Calls": 1791,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "JyotiBT27",
            "Calls": 773,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "KaifBT2",
            "Calls": 1929,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "Kajal2146",
            "Calls": 1413,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "KajalBT2",
            "Calls": 2704,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "KajalBT23",
            "Calls": 2022,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "KajalBT25",
            "Calls": 1194,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "Karan2260",
            "Calls": 1468,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "KashishBT26",
            "Calls": 2286,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "KavitaBT12",
            "Calls": 2827,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "Kishan642",
            "Calls": 2193,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "KunalBT9",
            "Calls": 2160,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "ManishBT16",
            "Calls": 1626,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "ManishBT24",
            "Calls": 2085,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "ManojBT27",
            "Calls": 1047,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "ManzoorBT2HYD",
            "Calls": 815,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "Mayank1BT16",
            "Calls": 1243,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "Meena1560",
            "Calls": 2812,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "Minat1628",
            "Calls": 2003,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "MisbahBT18",
            "Calls": 3349,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "Mohit1719",
            "Calls": 2299,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "MubassiraBT14HYD",
            "Calls": 1583,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "MuzammilBT2HYD",
            "Calls": 1829,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "NadeemBT23",
            "Calls": 1949,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "Neeraj1854",
            "Calls": 2119,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "NikhilBT31",
            "Calls": 2096,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "NishaBT8",
            "Calls": 2760,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "NishatBT5",
            "Calls": 2249,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "Nitin2220",
            "Calls": 2131,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "NitinBT12",
            "Calls": 2292,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "NoorBT1",
            "Calls": 2405,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "PardeepBT10",
            "Calls": 2783,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "PawanBT24",
            "Calls": 2036,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "PinkiBT23",
            "Calls": 2164,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "PoojaBT24",
            "Calls": 2561,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "PoojaBT28",
            "Calls": 2687,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "PrathamBT27",
            "Calls": 2091,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "PreetiBT27",
            "Calls": 1982,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "PreetiBT5",
            "Calls": 3354,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "PriyaBT26",
            "Calls": 2218,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "Rahil2181",
            "Calls": 1687,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "Rahul2600",
            "Calls": 1633,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "Rahul533",
            "Calls": 2568,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "Rahul756",
            "Calls": 2106,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "RahulBT23",
            "Calls": 2322,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "RahulBT6",
            "Calls": 992,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "RajaBT27",
            "Calls": 1912,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "Rajeev295",
            "Calls": 1606,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "Rajesh1768",
            "Calls": 3487,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "RashidBT27",
            "Calls": 1704,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "RashidBT28",
            "Calls": 880,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "Rehnuma2364",
            "Calls": 3168,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "RekhaBT36",
            "Calls": 2709,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "RishiBT23",
            "Calls": 2937,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "RitikaBT28",
            "Calls": 60,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "RiyaBT22",
            "Calls": 1841,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "Rizwan1722",
            "Calls": 1953,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "Rohit2291",
            "Calls": 2692,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "RohitBT30",
            "Calls": 3274,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "SaadBT15HYD",
            "Calls": 892,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "SaadBT16",
            "Calls": 2744,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "SadabBT15HYD",
            "Calls": 631,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "Sagar2039",
            "Calls": 2385,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "SagarBT18",
            "Calls": 2093,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "Sahil3259",
            "Calls": 2364,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "SahilBT23",
            "Calls": 2130,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "SajiyaBT25",
            "Calls": 2372,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "SalmanBT23",
            "Calls": 2635,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "Samad1626",
            "Calls": 71,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "SamadBT23",
            "Calls": 2009,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "SameedBT8",
            "Calls": 1123,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "Sandeep1695",
            "Calls": 186,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "SandeepBT20",
            "Calls": 2483,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "SapnaBT3",
            "Calls": 3140,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "SatishBT11",
            "Calls": 1999,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "SaudBT15",
            "Calls": 2035,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "Saurabh636",
            "Calls": 665,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "SaurabhBT5",
            "Calls": 2442,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "ShahbazBT8",
            "Calls": 3331,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "Shahid2619",
            "Calls": 2116,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "ShameenBT5",
            "Calls": 1824,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "SheetalBT23",
            "Calls": 2562,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "ShehnazBT25",
            "Calls": 2348,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "Shivam2100",
            "Calls": 1741,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "ShivaniBT26",
            "Calls": 1916,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "ShivaniBT3",
            "Calls": 2684,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "ShivBT31",
            "Calls": 1543,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "ShoaibBT46",
            "Calls": 2436,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "ShravanBT13",
            "Calls": 1771,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "ShubhamBT22",
            "Calls": 1064,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "Simran_TL",
            "Calls": 162,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "SnehaBT15",
            "Calls": 2847,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "SomnathBT23",
            "Calls": 2304,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "SonaliBT11",
            "Calls": 2408,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "Suhail_TL",
            "Calls": 116,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "SuhailBT19",
            "Calls": 2240,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "SuhailBT23",
            "Calls": 2010,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "SumanBT20",
            "Calls": 3181,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "SurajBT18",
            "Calls": 2375,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "TabassumBT14HYD",
            "Calls": 1529,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "TalhaBT19",
            "Calls": 2896,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "TamannaBT21",
            "Calls": 2790,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "TushantBT9",
            "Calls": 2086,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "Ubaid2225",
            "Calls": 2858,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "UjaliBT12",
            "Calls": 2521,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "UmaBT3",
            "Calls": 2467,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "Umair2744",
            "Calls": 2360,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "UnaizBT5",
            "Calls": 1241,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "UrvashiBT22",
            "Calls": 2183,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "UsamaBT28",
            "Calls": 708,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "Uzair3484",
            "Calls": 1840,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "VaishaliBT25",
            "Calls": 744,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "VickyBT22",
            "Calls": 1372,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "VishalBT47",
            "Calls": 2315,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "VishnuBT10",
            "Calls": 2374,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "VivekBT15",
            "Calls": 748,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "WahajBT25",
            "Calls": 243,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "WasifBT15",
            "Calls": 2848,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "YashBT6",
            "Calls": 84,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "YashikaBT5",
            "Calls": 2411,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "YogitaBT25",
            "Calls": 1638,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "YuvrajBT12",
            "Calls": 1831,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "ZahidBT19",
            "Calls": 2900,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "Zaid2521",
            "Calls": 3241,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "ZaidBT9",
            "Calls": 3053,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        },
        {
            "Campaign": "ZohaibBT13",
            "Calls": 1916,
            "Orders": 0,
            "Verified": 0,
            "Verified Amount": 0,
            "Verified Ticket Size": 0,
            "Order Conversion": "0%",
            "Verified Conversion": "0%",
            "Verification %": "0%",
            "RPC (Revenue per Call)": 0
        }
    ]
}