import { Model, DataTypes } from 'sequelize';
import { getPGSequelize } from '../../connections/index.js';

class AcdIntervalDenormalizedEntity extends Model {}

AcdIntervalDenormalizedEntity.init(
  {
    // unique_id is used as primary key (table has no explicit PK constraint)
    unique_id:                      { type: DataTypes.BIGINT,    primaryKey: true },

    setup_id:                       { type: DataTypes.STRING,    allowNull: true },
    setup_name:                     { type: DataTypes.STRING,    allowNull: true },
    ch_archive_id:                  { type: DataTypes.BIGINT,    allowNull: true },
    rah_archive_id:                 { type: DataTypes.BIGINT,    allowNull: true },
    rrh_archive_id:                 { type: DataTypes.BIGINT,    allowNull: true },
    rch_archive_id:                 { type: DataTypes.BIGINT,    allowNull: true },
    uch_archive_id:                 { type: DataTypes.BIGINT,    allowNull: true },
    ch_setup_time:                  { type: DataTypes.INTEGER,   allowNull: true },
    ch_ringing_time:                { type: DataTypes.INTEGER,   allowNull: true },
    ch_ringing_start_time:          { type: DataTypes.DATE,      allowNull: true },
    ch_call_id:                     { type: DataTypes.STRING,    allowNull: true },
    ch_call_leg_id:                 { type: DataTypes.STRING,    allowNull: true },
    ch_contact_center_id:           { type: DataTypes.INTEGER,   allowNull: true },
    ch_process_id:                  { type: DataTypes.INTEGER,   allowNull: true },
    ch_campaign_id:                 { type: DataTypes.INTEGER,   allowNull: true },
    ch_phone:                       { type: DataTypes.STRING,    allowNull: true },
    ch_crt_object_id:               { type: DataTypes.STRING,    allowNull: true },
    ch_customer_id:                 { type: DataTypes.BIGINT,    allowNull: true },
    ch_lead_id:                     { type: DataTypes.INTEGER,   allowNull: true },
    ch_lead_name:                   { type: DataTypes.STRING,    allowNull: true },
    ch_dialing_comments:            { type: DataTypes.STRING,    allowNull: true },
    ch_is_outbound:                 { type: DataTypes.BOOLEAN,   allowNull: true },
    ch_call_type:                   { type: DataTypes.STRING,    allowNull: true },
    ch_system_disposition:          { type: DataTypes.STRING,    allowNull: true },
    ch_date_added:                  { type: DataTypes.DATE,      allowNull: true },
    ch_call_result:                 { type: DataTypes.STRING,    allowNull: true },
    ch_hangup_cause:                { type: DataTypes.STRING,    allowNull: true },
    ch_hangup_cause_description:    { type: DataTypes.STRING,    allowNull: true },
    ch_hangup_cause_code:           { type: DataTypes.STRING,    allowNull: true },
    ch_hangup_first:                { type: DataTypes.BOOLEAN,   allowNull: true },
    ch_hangup_on_hold:              { type: DataTypes.BOOLEAN,   allowNull: true },
    ch_call_originate_time:         { type: DataTypes.DATE,      allowNull: true },
    ch_call_end_time:               { type: DataTypes.DATE,      allowNull: true },
    ch_ivr_time:                    { type: DataTypes.INTEGER,   allowNull: true },
    ch_talk_time:                   { type: DataTypes.INTEGER,   allowNull: true },
    ch_hold_time:                   { type: DataTypes.INTEGER,   allowNull: true },
    ch_recording_file_url:          { type: DataTypes.STRING,    allowNull: true },
    ch_nodeflow_id:                 { type: DataTypes.STRING,    allowNull: true },
    ch_actual_channel:              { type: DataTypes.STRING,    allowNull: true },
    ch_column_1:                    { type: DataTypes.STRING,    allowNull: true },
    ch_value_1:                     { type: DataTypes.STRING,    allowNull: true },
    ch_column_2:                    { type: DataTypes.STRING,    allowNull: true },
    ch_value_2:                     { type: DataTypes.STRING,    allowNull: true },
    ch_column_3:                    { type: DataTypes.STRING,    allowNull: true },
    ch_value_3:                     { type: DataTypes.STRING,    allowNull: true },
    ch_connection_state:            { type: DataTypes.STRING,    allowNull: true },
    ch_connection_state_data:       { type: DataTypes.STRING,    allowNull: true },
    ch_customer_source:             { type: DataTypes.STRING,    allowNull: true },
    ch_is_test_call:                { type: DataTypes.BOOLEAN,   allowNull: true },
    ch_num_attempts:                { type: DataTypes.INTEGER,   allowNull: true },
    ch_hangup_details:              { type: DataTypes.STRING,    allowNull: true },
    ch_related_crt_object_id:       { type: DataTypes.STRING,    allowNull: true },
    ch_nodeflow_meta_data:          { type: DataTypes.STRING,    allowNull: true },
    ch_dialed_call_details:         { type: DataTypes.STRING,    allowNull: true },
    ch_crm_url:                     { type: DataTypes.STRING,    allowNull: true },
    ch_src_phone:                   { type: DataTypes.STRING,    allowNull: true },
    ch_dst_phone:                   { type: DataTypes.STRING,    allowNull: true },
    ch_customer_data:               { type: DataTypes.STRING,    allowNull: true },
    udh_id:                         { type: DataTypes.STRING,    allowNull: true },
    udh_call_id:                    { type: DataTypes.STRING,    allowNull: true },
    udh_call_leg_id:                { type: DataTypes.STRING,    allowNull: true },
    udh_date_added:                 { type: DataTypes.DATE,      allowNull: true },
    udh_user_disposition_time:      { type: DataTypes.DATE,      allowNull: true },
    udh_transfer_time:              { type: DataTypes.DATE,      allowNull: true },
    udh_transfer_to:                { type: DataTypes.STRING,    allowNull: true },
    udh_disposition_details:        { type: DataTypes.STRING,    allowNull: true },
    udh_disposition_class:          { type: DataTypes.STRING,    allowNull: true },
    udh_disposition_code:           { type: DataTypes.STRING,    allowNull: true },
    udh_user_id:                    { type: DataTypes.STRING,    allowNull: true },
    udh_session_id:                 { type: DataTypes.STRING,    allowNull: true },
    udh_user_crt_object_id:         { type: DataTypes.STRING,    allowNull: true },
    udh_wrap_time:                  { type: DataTypes.INTEGER,   allowNull: true },
    udh_talk_time:                  { type: DataTypes.INTEGER,   allowNull: true },
    udh_working:                    { type: DataTypes.BOOLEAN,   allowNull: true },
    udh_campaign_team_id:           { type: DataTypes.INTEGER,   allowNull: true },
    udh_disposed_by_crm:            { type: DataTypes.BOOLEAN,   allowNull: true },
    udh_agent_queue_id:             { type: DataTypes.INTEGER,   allowNull: true },
    udh_auto_call_on_time:          { type: DataTypes.INTEGER,   allowNull: true },
    udh_auto_call_off_time:         { type: DataTypes.INTEGER,   allowNull: true },
    udh_user_connected_time:        { type: DataTypes.DATE,      allowNull: true },
    udh_user_disconnected_time:     { type: DataTypes.DATE,      allowNull: true },
    udh_campaign_id:                { type: DataTypes.INTEGER,   allowNull: true },
    udh_hold_time:                  { type: DataTypes.INTEGER,   allowNull: true },
    udh_association_type:           { type: DataTypes.STRING,    allowNull: true },
    udh_request_id:                 { type: DataTypes.STRING,    allowNull: true },
    udh_additional_parameters:      { type: DataTypes.STRING,    allowNull: true },
    udh_actual_channel:             { type: DataTypes.STRING,    allowNull: true },
    udh_call_context_id:            { type: DataTypes.INTEGER,   allowNull: true },
    udh_call_context_name:          { type: DataTypes.STRING,    allowNull: true },
    udh_phone:                      { type: DataTypes.STRING,    allowNull: true },
    uch_call_leg_id:                { type: DataTypes.STRING,    allowNull: true },
    uch_user_id:                    { type: DataTypes.STRING,    allowNull: true },
    uch_session_id:                 { type: DataTypes.STRING,    allowNull: true },
    uch_crt_object_id:              { type: DataTypes.STRING,    allowNull: true },
    uch_setup_time:                 { type: DataTypes.INTEGER,   allowNull: true },
    uch_ringing_time:               { type: DataTypes.INTEGER,   allowNull: true },
    uch_talk_time:                  { type: DataTypes.INTEGER,   allowNull: true },
    uch_date_added:                 { type: DataTypes.DATE,      allowNull: true },
    uch_id:                         { type: DataTypes.INTEGER,   allowNull: true },
    uch_phone:                      { type: DataTypes.STRING,    allowNull: true },
    uch_call_context_id:            { type: DataTypes.INTEGER,   allowNull: true },
    uch_ringing_start_time:         { type: DataTypes.DATE,      allowNull: true },
    uch_call_originate_time:        { type: DataTypes.DATE,      allowNull: true },
    rah_id:                         { type: DataTypes.BIGINT,    allowNull: true },
    rah_request_id:                 { type: DataTypes.STRING,    allowNull: true },
    rah_wait_time:                  { type: DataTypes.BIGINT,    allowNull: true },
    rah_actual_wait_time:           { type: DataTypes.BIGINT,    allowNull: true },
    rah_result:                     { type: DataTypes.STRING,    allowNull: true },
    rah_allocated_resource:         { type: DataTypes.STRING,    allowNull: true },
    rah_date_added:                 { type: DataTypes.DATE,      allowNull: true },
    rch_id:                         { type: DataTypes.BIGINT,    allowNull: true },
    rch_request_id:                 { type: DataTypes.STRING,    allowNull: true },
    rch_service_time:               { type: DataTypes.BIGINT,    allowNull: true },
    rch_allocated_resource:         { type: DataTypes.STRING,    allowNull: true },
    rch_date_added:                 { type: DataTypes.DATE,      allowNull: true },
    rrh_id:                         { type: DataTypes.BIGINT,    allowNull: true },
    rrh_request_id:                 { type: DataTypes.STRING,    allowNull: true },
    rrh_request_time:               { type: DataTypes.DATE,      allowNull: true },
    rrh_media_type:                 { type: DataTypes.STRING,    allowNull: true },
    rrh_constraint_type:            { type: DataTypes.STRING,    allowNull: true },
    rrh_constraint_id:              { type: DataTypes.INTEGER,   allowNull: true },
    rrh_mrt_object_id:              { type: DataTypes.STRING,    allowNull: true },
    rrh_source_context_id:          { type: DataTypes.INTEGER,   allowNull: true },
    rrh_request_type:               { type: DataTypes.STRING,    allowNull: true },
    rrh_association_type:           { type: DataTypes.STRING,    allowNull: true },
    rrh_date_added:                 { type: DataTypes.DATE,      allowNull: true },
    first_queue_hit:                { type: DataTypes.BOOLEAN,   allowNull: true },
    first_queue_answered:           { type: DataTypes.BOOLEAN,   allowNull: true },
    max_request_time:               { type: DataTypes.DATE,      allowNull: true },
    min_request_time:               { type: DataTypes.DATE,      allowNull: true },
    rrh_source_context_type:        { type: DataTypes.STRING,    allowNull: true },
    rec_no:                         { type: DataTypes.INTEGER,   allowNull: true },
    interval_start:                 { type: DataTypes.DATE,      allowNull: true },
    interval_end:                   { type: DataTypes.DATE,      allowNull: true },
    interval_start_30_minutes:      { type: DataTypes.DATE,      allowNull: true },
    interval_end_30_minutes:        { type: DataTypes.DATE,      allowNull: true },
    interval_start_hour:            { type: DataTypes.DATE,      allowNull: true },
    interval_end_hour:              { type: DataTypes.DATE,      allowNull: true },
    interval_start_day:             { type: DataTypes.DATE,      allowNull: true },
    interval_end_day:               { type: DataTypes.DATE,      allowNull: true },
    ch_setup_time_in_interval:      { type: DataTypes.BIGINT,    allowNull: true },
    uch_setup_time_in_interval:     { type: DataTypes.BIGINT,    allowNull: true },
    uch_ringing_time_in_interval:   { type: DataTypes.BIGINT,    allowNull: true },
    udh_talk_time_in_interval:      { type: DataTypes.BIGINT,    allowNull: true },
    udh_wrap_time_in_interval:      { type: DataTypes.BIGINT,    allowNull: true },
    rah_wait_time_in_interval:      { type: DataTypes.BIGINT,    allowNull: true },
    ch_ringing_time_in_interval:    { type: DataTypes.BIGINT,    allowNull: true },
    total_talk_time:                { type: DataTypes.INTEGER,   allowNull: true },
    total_wrap_time:                { type: DataTypes.INTEGER,   allowNull: true },
    total_wait_time:                { type: DataTypes.BIGINT,    allowNull: true },
    cumulative_wait_time:           { type: DataTypes.BIGINT,    allowNull: true },
    campaign_name:                  { type: DataTypes.STRING,    allowNull: true },
    username:                       { type: DataTypes.STRING,    allowNull: true },
    process_name:                   { type: DataTypes.STRING,    allowNull: true },
    queue_name:                     { type: DataTypes.STRING,    allowNull: true },
    udh_preview_duration:           { type: DataTypes.INTEGER,   allowNull: true },
    udh_preview_start_time:         { type: DataTypes.DATE,      allowNull: true },
    udh_preview_time_in_interval:   { type: DataTypes.BIGINT,    allowNull: true },
    archiver_comments:              { type: DataTypes.STRING,    allowNull: true },
    ch_filter_source:               { type: DataTypes.STRING,    allowNull: true },
    ch_filter_source_data:          { type: DataTypes.JSONB,     allowNull: true },
    ch_dialled_phone:               { type: DataTypes.STRING,    allowNull: true },
    ch_attempt_flow_detail:         { type: DataTypes.STRING,    allowNull: true },
    ch_dtmf_info:                   { type: DataTypes.STRING,    allowNull: true },
    udh_notes:                      { type: DataTypes.STRING,    allowNull: true },
    udh_customer_hold_time:         { type: DataTypes.INTEGER,   allowNull: true },
    ch_vq_request_id:               { type: DataTypes.STRING,    allowNull: true },
    ch_display_phone:               { type: DataTypes.STRING,    allowNull: true },
    ch_unique_identifier:           { type: DataTypes.STRING,    allowNull: true },
    ch_filter_group_source:         { type: DataTypes.JSONB,     allowNull: true },
    ch_callback_id:                 { type: DataTypes.STRING,    allowNull: true },
    udh_rec_no:                     { type: DataTypes.INTEGER,   allowNull: true },
  },
  {
    sequelize: getPGSequelize(),
    tableName: 'acd_interval_denormalized_entity',
    schema: 'public',
    timestamps: false,
    freezeTableName: true,
  }
);

export default AcdIntervalDenormalizedEntity;
