import { Model, DataTypes } from 'sequelize';
import { getMSSQLSequelize } from '../../connections/index.js';

class TblOrderDetails extends Model {}

TblOrderDetails.init(
  {
    id:                    { type: DataTypes.BIGINT,       primaryKey: true, autoIncrement: true },
    ptId:                  { type: DataTypes.STRING(50),   allowNull: true },
    OrderNo:               { type: DataTypes.STRING(50),   allowNull: true, unique: true },
    PId:                   { type: DataTypes.STRING(50),   allowNull: true },
    callType:              { type: DataTypes.INTEGER,      allowNull: true },
    name:                  { type: DataTypes.STRING(50),   allowNull: true },
    mobile:                { type: DataTypes.STRING(50),   allowNull: true },
    alterMob:              { type: DataTypes.STRING(50),   allowNull: true },
    Mobile3:               { type: DataTypes.STRING(15),   allowNull: true },
    Guradian:              { type: DataTypes.STRING(20),   allowNull: true },
    son_of:                { type: DataTypes.STRING(50),   allowNull: true },
    house_no:              { type: DataTypes.STRING(100),  allowNull: true },
    Street:                { type: DataTypes.STRING(100),  allowNull: true },
    Floor:                 { type: DataTypes.STRING(100),  allowNull: true },
    landmark:              { type: DataTypes.STRING(100),  allowNull: true },
    Landmark2:             { type: DataTypes.STRING(100),  allowNull: true },
    PostID:                { type: DataTypes.STRING(50),   allowNull: true },
    post:                  { type: DataTypes.STRING(100),  allowNull: true },
    tehseel:               { type: DataTypes.STRING(100),  allowNull: true },
    district:              { type: DataTypes.STRING(100),  allowNull: true },
    city:                  { type: DataTypes.STRING(100),  allowNull: true },
    state:                 { type: DataTypes.STRING(100),  allowNull: true },
    Country:               { type: DataTypes.STRING(100),  allowNull: true },
    pin_code:              { type: DataTypes.STRING(50),   allowNull: true },
    problem:               { type: DataTypes.TEXT,         allowNull: true },
    OtherProblem:          { type: DataTypes.TEXT,         allowNull: true },
    Problem_ID:            { type: DataTypes.STRING(10),   allowNull: true },
    comment:               { type: DataTypes.TEXT,         allowNull: true },
    disposition_Code:      { type: DataTypes.STRING(100),  allowNull: true },
    Discount:              { type: DataTypes.INTEGER,      allowNull: true },
    total_amount:          { type: DataTypes.INTEGER,      allowNull: true },
    gross_amount:          { type: DataTypes.INTEGER,      allowNull: true },
    cod:                   { type: DataTypes.STRING(20),   allowNull: true },
    doctor_name:           { type: DataTypes.STRING(100),  allowNull: true },
    verifier_name:         { type: DataTypes.STRING(100),  allowNull: true },
    dialer:                { type: DataTypes.INTEGER,      allowNull: true },
    dis_status:            { type: DataTypes.INTEGER,      allowNull: true },
    odate:                 { type: DataTypes.DATE,         allowNull: true },
    vdate:                 { type: DataTypes.DATE,         allowNull: true },
    createdOn:             { type: DataTypes.DATE,         allowNull: true },
    UpdatedOn:             { type: DataTypes.DATE,         allowNull: true },
    status:                { type: DataTypes.INTEGER,      allowNull: true },
    ass_flage:             { type: DataTypes.INTEGER,      allowNull: true },
    campaign_Id:           { type: DataTypes.INTEGER,      allowNull: true },
    detained_session:      { type: DataTypes.STRING(200),  allowNull: true },
    OrderDate:             { type: DataTypes.DATEONLY,     allowNull: true },
    OrderTime:             { type: DataTypes.TIME,         allowNull: true },
    UpdatedDate:           { type: DataTypes.DATEONLY,     allowNull: true },
    UpdatedTime:           { type: DataTypes.TIME,         allowNull: true },
    NumOfCalls:            { type: DataTypes.INTEGER,      allowNull: true },
    DownloadStatus:        { type: DataTypes.STRING(3),    allowNull: true },
    DispatchStatus:        { type: DataTypes.STRING(3),    allowNull: true },
    DispatchedDate:        { type: DataTypes.DATEONLY,     allowNull: true },
    ByCourier:             { type: DataTypes.STRING(50),   allowNull: true },
    rejected_reason:       { type: DataTypes.STRING(200),  allowNull: true },
    WayBillNo:             { type: DataTypes.STRING(50),   allowNull: true },
    FollowUpDate:          { type: DataTypes.DATE,         allowNull: true },
    DeniedReason:          { type: DataTypes.STRING(100),  allowNull: true },
    DeniedReasonID:        { type: DataTypes.INTEGER,      allowNull: true },
    CourierUpdatedOn:      { type: DataTypes.DATE,         allowNull: true },
    CourierUpdatedBy:      { type: DataTypes.STRING(50),   allowNull: true },
    CourtesyCall:          { type: DataTypes.INTEGER,      allowNull: true },
    CourtesyDate:          { type: DataTypes.DATE,         allowNull: true },
    ReOrderCall:           { type: DataTypes.INTEGER,      allowNull: true },
    ReOrderFollowup:       { type: DataTypes.DATE,         allowNull: true },
    UrgentOrder:           { type: DataTypes.INTEGER,      allowNull: true },
    UrgentOrderAmount:     { type: DataTypes.INTEGER,      allowNull: true },
    DelayDispatch:         { type: DataTypes.INTEGER,      allowNull: true },
    DelayDispatchDate:     { type: DataTypes.DATEONLY,     allowNull: true },
    AddressID:             { type: DataTypes.INTEGER,      allowNull: true },
    AddressUsedOn:         { type: DataTypes.DATEONLY,     allowNull: true },
    ReqCancel:             { type: DataTypes.STRING(10),   allowNull: true },
    CancelReason:          { type: DataTypes.STRING(100),  allowNull: true },
    UserByCancel:          { type: DataTypes.STRING(100),  allowNull: true },
    CanDate:               { type: DataTypes.DATE,         allowNull: true },
    CourierRemark:         { type: DataTypes.STRING(50),   allowNull: true },
    PushStatus:            { type: DataTypes.STRING(20),   allowNull: true },
    PushErrorDetails:      { type: DataTypes.STRING(500),  allowNull: true },
    ReConsultation:        { type: DataTypes.BOOLEAN,      allowNull: true },
    CHANNEL_ID:            { type: DataTypes.DECIMAL(4, 0), allowNull: true },
    OrderType:             { type: DataTypes.INTEGER,      allowNull: true },
    OnlineOrderNo:         { type: DataTypes.STRING(50),   allowNull: true },
    Disp_Verifier:         { type: DataTypes.STRING(50),   allowNull: true },
    Disp_Flag:             { type: DataTypes.INTEGER,      allowNull: true },
    Disp_Code:             { type: DataTypes.STRING(50),   allowNull: true },
    Disp_Date:             { type: DataTypes.DATE,         allowNull: true },
    CourierName:           { type: DataTypes.STRING(70),   allowNull: true },
    DiscountReq:           { type: DataTypes.INTEGER,      allowNull: true },
    PrefercallTime:        { type: DataTypes.TIME,         allowNull: true },
    PushDate:              { type: DataTypes.DATE,         allowNull: true },
    ratingflag:            { type: DataTypes.BOOLEAN,      allowNull: true },
    AgentID:               { type: DataTypes.INTEGER,      allowNull: true },
    VerifiiedBy:           { type: DataTypes.STRING(10),   allowNull: true },
    EscalationId:          { type: DataTypes.INTEGER,      allowNull: true },
    Source:                { type: DataTypes.STRING(15),   allowNull: true },
    IsCounsellingAssign:   { type: DataTypes.BOOLEAN,      allowNull: true, defaultValue: false },
    CouselerName:          { type: DataTypes.STRING(50),   allowNull: true },
    CounsellingPtid:       { type: DataTypes.STRING(50),   allowNull: true },
    ReVerify:              { type: DataTypes.BOOLEAN,      allowNull: true },
    NewPatientVerification:{ type: DataTypes.BOOLEAN,      allowNull: true, defaultValue: false },
    SalesDelayDispatch:    { type: DataTypes.INTEGER,      allowNull: true },
    SalesDelayDispatchDate:{ type: DataTypes.DATEONLY,     allowNull: true },
    IsSMSSent:             { type: DataTypes.INTEGER,      allowNull: true, defaultValue: 0 },
    Counsellingid:         { type: DataTypes.INTEGER,      allowNull: true },
    DelayDate:             { type: DataTypes.DATEONLY,     allowNull: true },
    JobStatus:             { type: DataTypes.INTEGER,      allowNull: true, defaultValue: 1 },
    JobStatusUpdate:       { type: DataTypes.INTEGER,      allowNull: true },
  },
  {
    sequelize: getMSSQLSequelize(),
    tableName: 'tblOrderDetails',
    schema: 'dbo',
    timestamps: false,
    freezeTableName: true,
  }
);

export default TblOrderDetails;
